# Generated by Django 5.0.4 on 2024-05-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0002_auto_20200524_1511"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
